language: php

os:
  - linux
dist: bionic

php:
  - '8.0'
  - '8.1.0'

install: composer install

script: XDEBUG_MODE=coverage php ./vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
